const altMap = {
  "bz3x": {
    "models/BZ3x/610/front-view.jpg": "GAC Toyota BZ3X — передній вигляд",
    "models/BZ3x/610/front-left.jpg": "GAC Toyota BZ3X — передній лівий ракурс",
    "models/BZ3x/610/front-right.jpg": "GAC Toyota BZ3X — передній правий ракурс",
    "models/BZ3x/610/rear-view.jpg": "GAC Toyota BZ3X — задній вигляд",
    "models/BZ3x/610/rear-left.jpg": "GAC Toyota BZ3X — задній лівий ракурс",
    "models/BZ3x/610/rear-right.jpg": "GAC Toyota BZ3X — задній правий ракурс",
    "models/BZ3x/610/sunroof.jpg": "GAC Toyota BZ3X — панорамний дах",
    "models/BZ3x/610/left-side-view.jpg": "GAC Toyota BZ3X — лівий бік",
    "models/BZ3x/610/bottom-view.jpg": "GAC Toyota BZ3X — нижня частина авто",
    "models/BZ3x/610/charging-port.jpg": "GAC Toyota BZ3X — зарядний порт",
    "models/BZ3x/610/key.jpg": "GAC Toyota BZ3X — ключ",
    "models/BZ3x/610/with-sunroof.webp": "GAC Toyota BZ3X — версія з люком",
    "models/BZ3x/610/without-sunroof.webp": "GAC Toyota BZ3X — версія без люка",
    "models/BZ3x/610/trunk.webp": "GAC Toyota BZ3X — багажник",
    "models/BZ3x/610/trunk-2.webp": "GAC Toyota BZ3X — багажник (варіант 2)",
    "models/BZ3x/610/trunk-white.webp": "GAC Toyota BZ3X — багажник (білий)",
    "models/BZ3x/610/dashboard-white.webp": "GAC Toyota BZ3X — панель приладів (білий салон)",
    "models/BZ3x/610/front-driving-white.webp": "GAC Toyota BZ3X — рух спереду (білий)",
    "models/BZ3x/610/orange-interior-1.jpg": "GAC Toyota BZ3X — салон (помаранчевий)",
    "models/BZ3x/610/orange-dashboard.jpg": "GAC Toyota BZ3X — панель приладів (помаранчева)",
    "models/BZ3x/610/orange-rear.jpg": "GAC Toyota BZ3X — задній ряд (помаранчевий)",
    "models/BZ3x/610/orange-rear-seat.jpg": "GAC Toyota BZ3X — задні сидіння (помаранчеві)",
    "models/BZ3x/610/orange-left-door.jpg": "GAC Toyota BZ3X — двері зліва (помаранчеві)",
    "models/BZ3x/610/orange-driving-left.jpg": "GAC Toyota BZ3X — рух зліва (помаранчевий)",
    "models/BZ3x/610/main-angle.webp": "GAC Toyota BZ3X — основний ракурс",
    "models/BZ3x/610/black/backseat.jpg": "GAC Toyota BZ3X — задні сидіння (чорний)",
    "models/BZ3x/610/black/driving.jpg": "GAC Toyota BZ3X — рух (чорний)",
    "models/BZ3x/610/black/trunk.jpg": "GAC Toyota BZ3X — багажник (чорний)"
  },

  "song-plus": {
    "models/song-plus/front-view.jpg": "BYD Song Plus EV — передній вигляд",
    "models/song-plus/side-view.jpg": "BYD Song Plus EV — вигляд збоку",
    "models/song-plus/front-left.jpg": "BYD Song Plus EV — передній лівий ракурс",
    "models/song-plus/front-right.jpg": "BYD Song Plus EV — передній правий ракурс",
    "models/song-plus/rear-left.jpg": "BYD Song Plus EV — задній лівий ракурс",
    "models/song-plus/trunk.jpg": "BYD Song Plus EV — багажник",
    "models/song-plus/rear-seat.jpg": "BYD Song Plus EV — задні сидіння",
    "models/song-plus/sunroof.jpg": "BYD Song Plus EV — панорамний дах",
    "models/song-plus/rear-seat-2.jpg": "BYD Song Plus EV — задні сидіння (варіант 2)",
    "models/song-plus/charging-port-1.jpg": "BYD Song Plus EV — зарядний порт (1)",
    "models/song-plus/charging-port-2.jpg": "BYD Song Plus EV — зарядний порт (2)",
    "models/song-plus/front-detail.jpg": "BYD Song Plus EV — передня оптика",
    "models/song-plus/gear-lever.jpg": "BYD Song Plus EV — селектор передач",
    "models/song-plus/motor-compartment.jpg": "BYD Song Plus EV — моторний відсік",
    "models/song-plus/key.jpg": "BYD Song Plus EV — ключ",
    "models/song-plus/driving-cabin.jpg": "BYD Song Plus EV — салон під час руху"
  },

  "yuan-plus": {
    "models/yuan-plus/front-view.jpg": "BYD Yuan Plus — передній вигляд",
    "models/yuan-plus/side-view.jpg": "BYD Yuan Plus — вигляд збоку",
    "models/yuan-plus/front-left.jpg": "BYD Yuan Plus — передній лівий ракурс",
    "models/yuan-plus/front-right.jpg": "BYD Yuan Plus — передній правий ракурс",
    "models/yuan-plus/with-sunroof.jpg": "BYD Yuan Plus — версія з люком",
    "models/yuan-plus/without-sunroof.jpg": "BYD Yuan Plus — версія без люка",
    "models/yuan-plus/driver-seat.jpg": "BYD Yuan Plus — водійське сидіння",
    "models/yuan-plus/passenger-seat.jpg": "BYD Yuan Plus — пасажирське сидіння",
    "models/yuan-plus/rear-view.jpg": "BYD Yuan Plus — задній вигляд",
    "models/yuan-plus/rear-seat.jpg": "BYD Yuan Plus — задні сидіння",
    "models/yuan-plus/front-detail.jpg": "BYD Yuan Plus — передня оптика",
    "models/yuan-plus/right-side-view.jpg": "BYD Yuan Plus — правий бік",
    "models/yuan-plus/headlight-detail.jpg": "BYD Yuan Plus — фара крупним планом",
    "models/yuan-plus/engine-bay.jpg": "BYD Yuan Plus — моторний відсік",
    "models/yuan-plus/key.jpg": "BYD Yuan Plus — ключ",
    "models/yuan-plus/trunk.jpg": "BYD Yuan Plus — багажник",
    "models/yuan-plus/charging-1.jpg": "BYD Yuan Plus — зарядка (1)",
    "models/yuan-plus/charging-2.jpg": "BYD Yuan Plus — зарядка (2)",
    "models/yuan-plus/steering-wheel.webp": "BYD Yuan Plus — кермо",
    "models/yuan-plus/driving.webp": "BYD Yuan Plus — рух",
    "models/yuan-plus/rear-left.jpg": "BYD Yuan Plus — задній лівий ракурс"
  },

  "qin-l": {
    "models/qin-l/front-view.jpg": "BYD Qin L EV — передній вигляд",
    "models/qin-l/side-view.jpg": "BYD Qin L EV — вигляд збоку",
    "models/qin-l/front-left.jpg": "BYD Qin L EV — передній лівий ракурс",
    "models/qin-l/front-right.jpg": "BYD Qin L EV — передній правий ракурс",
    "models/qin-l/trunk.jpg": "BYD Qin L EV — багажник",
    "models/qin-l/rear-view.jpg": "BYD Qin L EV — задній вигляд",
    "models/qin-l/steering-wheel.jpg": "BYD Qin L EV — кермо",
    "models/qin-l/key.jpg": "BYD Qin L EV — ключ",
    "models/qin-l/driving-cabin.jpg": "BYD Qin L EV — салон",
    "models/qin-l/charging-port.jpg": "BYD Qin L EV — зарядний порт",
    "models/qin-l/hood.jpg": "BYD Qin L EV — підкапотний простір"
  },

  "id4": {
    "models/id4/front-view.jpg": "Volkswagen ID.4 — передній вигляд",
    "models/id4/front-left.jpg": "Volkswagen ID.4 — передній лівий ракурс",
    "models/id4/front-right.jpg": "Volkswagen ID.4 — передній правий ракурс",
    "models/id4/rear-left.jpg": "Volkswagen ID.4 — задній лівий ракурс",
    "models/id4/trunk.jpg": "Volkswagen ID.4 — багажник",
    "models/id4/rear-seat.jpg": "Volkswagen ID.4 — задні сидіння",
    "models/id4/sunroof.jpg": "Volkswagen ID.4 — панорамний дах",
    "models/id4/motor-compartment.jpg": "Volkswagen ID.4 — моторний відсік",
    "models/id4/key.jpg": "Volkswagen ID.4 — ключ",
    "models/id4/charging-port.jpg": "Volkswagen ID.4 — зарядний порт",
    "models/id4/charging-port-2.jpg": "Volkswagen ID.4 — зарядний порт (2)",
    "models/id4/driving-cabin.jpg": "Volkswagen ID.4 — салон"
  },

  "corolla": {
    "models/corolla/front-view.jpg": "Toyota Corolla Hybrid — передній вигляд",
    "models/corolla/side-view.jpg": "Toyota Corolla Hybrid — вигляд збоку",
    "models/corolla/front-left.jpg": "Toyota Corolla Hybrid — передній лівий ракурс",
    "models/corolla/front-right.jpg": "Toyota Corolla Hybrid — передній правий ракурс",
    "models/corolla/trunk.jpg": "Toyota Corolla Hybrid — багажник",
    "models/corolla/rear-view.jpg": "Toyota Corolla Hybrid — задній вигляд",
    "models/corolla/rear-seat.jpg": "Toyota Corolla Hybrid — задні сидіння",
    "models/corolla/detail.jpg": "Toyota Corolla Hybrid — деталі салону",
    "models/corolla/engine.jpg": "Toyota Corolla Hybrid — моторний відсік",
    "models/corolla/key.jpg": "Toyota Corolla Hybrid — ключ",
    "models/corolla/driving.jpg": "Toyota Corolla Hybrid — рух"
  },

  "camry": {
    "models/camry/front-view.jpg": "Toyota Camry 2.0HG — передній вигляд",
    "models/camry/side-view.jpg": "Toyota Camry 2.0HG — вигляд збоку",
    "models/camry/front-left.jpg": "Toyota Camry 2.0HG — передній лівий ракурс",
    "models/camry/rear-right.jpg": "Toyota Camry 2.0HG — задній правий ракурс",
    "models/camry/trunk.jpg": "Toyota Camry 2.0HG — багажник",
    "models/camry/rear-seat.jpg": "Toyota Camry 2.0HG — задні сидіння",
    "models/camry/detail.jpg": "Toyota Camry 2.0HG — деталі салону",
    "models/camry/steering-wheel.jpg": "Toyota Camry 2.0HG — кермо",
    "models/camry/key.jpg": "Toyota Camry 2.0HG — ключ",
    "models/camry/camry-badge.jpg": "Toyota Camry 2.0HG — емблема Camry",
    "models/camry/driver-seat.jpg": "Toyota Camry 2.0HG — водійське сидіння",
    "models/camry/dashboard.jpg": "Toyota Camry 2.0HG — панель приладів",
    "models/camry/passenger-seat.jpg": "Toyota Camry 2.0HG — пасажирське сидіння"
  },

  "corolla-cross": {
    "models/corolla-cross/front-view.jpg": "Toyota Corolla Cross — передній вигляд",
    "models/corolla-cross/side-view.jpg": "Toyota Corolla Cross — вигляд збоку",
    "models/corolla-cross/front-left.jpg": "Toyota Corolla Cross — передній лівий ракурс",
    "models/corolla-cross/front-right.jpg": "Toyota Corolla Cross — передній правий ракурс",
    "models/corolla-cross/trunk.jpg": "Toyota Corolla Cross — багажник",
    "models/corolla-cross/rear-seat.jpg": "Toyota Corolla Cross — задні сидіння",
    "models/corolla-cross/rear-view.jpg": "Toyota Corolla Cross — задній вигляд",
    "models/corolla-cross/key.jpg": "Toyota Corolla Cross — ключ",
    "models/corolla-cross/driving-cabin.jpg": "Toyota Corolla Cross — салон",
    "models/corolla-cross/with-sunroof.jpg": "Toyota Corolla Cross — версія з люком",
    "models/corolla-cross/without-sunroof.jpg": "Toyota Corolla Cross — версія без люка",
    "models/corolla-cross/engine.jpg": "Toyota Corolla Cross — моторний відсік",
    "models/corolla-cross/engine-2.jpg": "Toyota Corolla Cross — моторний відсік (2)",
    "models/corolla-cross/front-seat.jpg": "Toyota Corolla Cross — передні сидіння"
  },

  "rav4": {
    "models/rav4/front-view.jpg": "Toyota RAV4 Hybrid — передній вигляд",
    "models/rav4/side-view.jpg": "Toyota RAV4 Hybrid — вигляд збоку",
    "models/rav4/front-left.jpg": "Toyota RAV4 Hybrid — передній лівий ракурс",
    "models/rav4/front-right.jpg": "Toyota RAV4 Hybrid — передній правий ракурс",
    "models/rav4/trunk.jpg": "Toyota RAV4 Hybrid — багажник",
    "models/rav4/rear-view.jpg": "Toyota RAV4 Hybrid — задній вигляд",
    "models/rav4/rear-seat.jpg": "Toyota RAV4 Hybrid — задні сидіння",
    "models/rav4/key.jpg": "Toyota RAV4 Hybrid — ключ",
    "models/rav4/driving.jpg": "Toyota RAV4 Hybrid — рух",
    "models/rav4/driver-door.jpg": "Toyota RAV4 Hybrid — двері водія",
    "models/rav4/engine.jpg": "Toyota RAV4 Hybrid — моторний відсік"
  },

  "seal-06": {
    "models/seal-06/front-view.jpg": "BYD Seal 06 EV — передній вигляд",
    "models/seal-06/side-view.jpg": "BYD Seal 06 EV — вигляд збоку",
    "models/seal-06/front-left.jpg": "BYD Seal 06 EV — передній лівий ракурс",
    "models/seal-06/front-right.jpg": "BYD Seal 06 EV — передній правий ракурс",
    "models/seal-06/rear-left.jpg": "BYD Seal 06 EV — задній лівий ракурс",
    "models/seal-06/rear-right.jpg": "BYD Seal 06 EV — задній правий ракурс",
    "models/seal-06/trunk.jpg": "BYD Seal 06 EV — багажник",
    "models/seal-06/rear-seat.jpg": "BYD Seal 06 EV — задні сидіння",
    "models/seal-06/detail.jpg": "BYD Seal 06 EV — деталі салону",
    "models/seal-06/sunroof.jpg": "BYD Seal 06 EV — панорамний дах",
    "models/seal-06/key.jpg": "BYD Seal 06 EV — ключ",
    "models/seal-06/driving.jpg": "BYD Seal 06 EV — рух",
    "models/seal-06/motor-detail.jpg": "BYD Seal 06 EV — моторний відсік",
    "models/seal-06/startup.jpg": "BYD Seal 06 EV — запуск системи"
  },

    "audi-q4": {
    "models/audi-q4/front-view.jpg": "Audi Q4 e-tron 40 — передній вигляд",
    "models/audi-q4/side-view.jpg": "Audi Q4 e-tron 40 — вигляд збоку",
    "models/audi-q4/front-left.jpg": "Audi Q4 e-tron 40 — передній лівий ракурс",
    "models/audi-q4/front-right.jpg": "Audi Q4 e-tron 40 — передній правий ракурс",
    "models/audi-q4/rear-left.jpg": "Audi Q4 e-tron 40 — задній лівий ракурс",
    "models/audi-q4/rear-seat.jpg": "Audi Q4 e-tron 40 — задні сидіння",
    "models/audi-q4/steering-wheel.jpg": "Audi Q4 e-tron 40 — кермо",
    "models/audi-q4/sunroof.jpg": "Audi Q4 e-tron 40 — панорамний дах",
    "models/audi-q4/motor.jpg": "Audi Q4 e-tron 40 — моторний відсік",
    "models/audi-q4/charging.jpg": "Audi Q4 e-tron 40 — зарядка",
    "models/audi-q4/key.jpg": "Audi Q4 e-tron 40 — ключ",
    "models/audi-q4/driving.jpg": "Audi Q4 e-tron 40 — рух",
    "models/audi-q4/side-view-2.jpg": "Audi Q4 e-tron 40 — вигляд збоку (варіант 2)",
    "models/audi-q4/driver-door.jpg": "Audi Q4 e-tron 40 — двері водія"
    }
}