/* Kunze Auto - Єдина структура даних для всіх авто */

const cars = [
  {
    id: "bz3x",
    slug: "bz3x",
    brand: "GAC Toyota",
    model: "BZ3X",
    year: 2025,
    heroImage: "models/BZ3x/610/front-view.jpg",
    descriptionShort: "Преміальна динаміка. Великий запас ходу. Офіційна гарантія виробника.",
    video: "src/videos/bozhi-3x-trailer.mp4",

    trims: [
      {
        id: "610-max",
        name: "BZ3X 610 Max",
        type: "EV",
        colors: ["Білий", "Сірий", "Чорний"],
        rangeKm: 610,
        batteryKwh: 67.92,
        powerHp: 152,
        drive: "Передній",
        price: 38500,
      },
      {
        id: "520-pro",
        name: "BZ3X 520 Pro",
        type: "EV",
        colors: ["Білий"],
        rangeKm: 520,
        batteryKwh: 58.37,
        powerHp: 152,
        drive: "Передній",
        price: 34600,
      },
      {
        id: "520-pro-plus",
        name: "BZ3X 520 Pro+",
        type: "EV",
        colors: ["Білий", "Сірий"],
        rangeKm: 520,
        batteryKwh: 58.37,
        powerHp: 152,
        drive: "Передній",
        price: 36000,
      },
    ],
    gallery: [
      "models/BZ3x/610/front-view.jpg",
      "models/BZ3x/610/front-left.jpg",
      "models/BZ3x/610/front-right.jpg",
      "models/BZ3x/610/rear-view.jpg",
      "models/BZ3x/610/rear-left.jpg",
      "models/BZ3x/610/rear-right.jpg",
      "models/BZ3x/610/sunroof.jpg",
      "models/BZ3x/610/left-side-view.jpg",
      "models/BZ3x/610/bottom-view.jpg",
      "models/BZ3x/610/charging-port.jpg",
      "models/BZ3x/610/key.jpg",
      "models/BZ3x/610/with-sunroof.webp",
      "models/BZ3x/610/without-sunroof.webp",
      "models/BZ3x/610/trunk.webp",
      "models/BZ3x/610/trunk-2.webp",
      "models/BZ3x/610/trunk-white.webp",
      "models/BZ3x/610/dashboard-white.webp",
      "models/BZ3x/610/front-driving-white.webp",
      "models/BZ3x/610/orange-interior-1.jpg",
      "models/BZ3x/610/orange-dashboard.jpg",
      "models/BZ3x/610/orange-rear.jpg",
      "models/BZ3x/610/orange-rear-seat.jpg",
      "models/BZ3x/610/orange-left-door.jpg",
      "models/BZ3x/610/orange-driving-left.jpg",
      "models/BZ3x/610/main-angle.webp",
      "models/BZ3x/610/black/backseat.jpg",
      "models/BZ3x/610/black/driving.jpg",
      "models/BZ3x/610/black/trunk.jpg",
    ], 
  },

  {
    id: "song-plus",
    slug: "song-plus",
    brand: "BYD",
    model: "Song Plus EV",
    year: 2025,
    stock: 6,
    heroImage: "models/song-plus/front-view.jpg",
    descriptionShort: "Компактний електромобіль з гарною автономією",
    trims: [
      {
        id: "520-lux",
        name: "Song Plus EV 520",
        type: "EV",
        price: 33500,
        colors: ["Білий", "Сірий"],
        rangeKm: 520,
        batteryKwh: 58.37,
        powerHp: 152,
        drive: "Передній",
      },
    ],
    gallery: [
      "models/song-plus/front-view.jpg",
      "models/song-plus/side-view.jpg",
      "models/song-plus/front-left.jpg",
      "models/song-plus/front-right.jpg",
      "models/song-plus/rear-left.jpg",
      "models/song-plus/trunk.jpg",
      "models/song-plus/rear-seat.jpg",
      "models/song-plus/sunroof.jpg",
      "models/song-plus/rear-seat-2.jpg",
      "models/song-plus/charging-port-1.jpg",
      "models/song-plus/charging-port-2.jpg",
      "models/song-plus/front-detail.jpg",
      "models/song-plus/gear-lever.jpg",
      "models/song-plus/motor-compartment.jpg",
      "models/song-plus/key.jpg",
      "models/song-plus/driving-cabin.jpg",
    ],
  },

  {
    id: "yuan-plus",
    slug: "yuan-plus",
    brand: "BYD",
    model: "Yuan Plus",
    year: 2025,
    stock: 5,
    heroImage: "models/yuan-plus/front-view.jpg",
    descriptionShort: "Стильний кросовер з люком і без",
    trims: [
      { id: "sunroof", name: "Yuan Plus (з люком)", price: 30500, colors: ["Білий"], rangeKm: 550, batteryKwh: 70, powerHp: 180, drive: "Повний" },
      { id: "no-sunroof", name: "Yuan Plus (без люка)", price: 29200, colors: ["Чорний"], rangeKm: 550, batteryKwh: 70, powerHp: 180, drive: "Повний" },
    ],
    gallery: [
      "models/yuan-plus/front-view.jpg",
      "models/yuan-plus/side-view.jpg",
      "models/yuan-plus/front-left.jpg",
      "models/yuan-plus/front-right.jpg",
      "models/yuan-plus/with-sunroof.jpg",
      "models/yuan-plus/without-sunroof.jpg",
      "models/yuan-plus/driver-seat.jpg",
      "models/yuan-plus/passenger-seat.jpg",
      "models/yuan-plus/rear-view.jpg",
      "models/yuan-plus/rear-seat.jpg",
      "models/yuan-plus/front-detail.jpg",
      "models/yuan-plus/right-side-view.jpg",
      "models/yuan-plus/headlight-detail.jpg",
      "models/yuan-plus/engine-bay.jpg",
      "models/yuan-plus/key.jpg",
      "models/yuan-plus/trunk.jpg",
      "models/yuan-plus/charging-1.jpg",
      "models/yuan-plus/charging-2.jpg",
      "models/yuan-plus/steering-wheel.webp",
      "models/yuan-plus/driving.webp",
      "models/yuan-plus/rear-left.jpg",
    ],
  },

  {
    id: "qin-l",
    slug: "qin-l",
    brand: "BYD",
    model: "Qin L EV",
    year: 2025,
    heroImage: "models/qin-l/front-view.jpg",
    descriptionShort: "Електричний седан з відмінною батареєю",
    trims: [
      { id: "470", name: "Qin L 470", price: 26800, stock: 1, colors: ["Білий"], rangeKm: 470, batteryKwh: 55, powerHp: 150, drive: "Передній" },
      { id: "545", name: "Qin L 545", price: 28200, stock: 3, colors: ["Чорний"], rangeKm: 545, batteryKwh: 65, powerHp: 150, drive: "Передній" },
    ],
    gallery: [
      "models/qin-l/front-view.jpg",
      "models/qin-l/side-view.jpg",
      "models/qin-l/front-left.jpg",
      "models/qin-l/front-right.jpg",
      "models/qin-l/trunk.jpg",
      "models/qin-l/rear-view.jpg",
      "models/qin-l/steering-wheel.jpg",
      "models/qin-l/key.jpg",
      "models/qin-l/driving-cabin.jpg",
      "models/qin-l/charging-port.jpg",
      "models/qin-l/hood.jpg",
    ],
  },

  {
    id: "id4",
    slug: "id4",
    brand: "Volkswagen",
    model: "ID.4 Pure",
    year: 2026,
    stock: 20,
    heroImage: "models/id4/front-view.jpg",
    descriptionShort: "Надійний електромобіль від Volkswagen",
    trims: [
      { id: "pure", name: "ID.4 Pure", price: 30600, colors: ["Білий"], rangeKm: 550, batteryKwh: 77, powerHp: 204, drive: "Передній" },
    ],
    gallery: [
      "models/id4/front-view.jpg",
      "models/id4/front-left.jpg",
      "models/id4/front-right.jpg",
      "models/id4/rear-left.jpg",
      "models/id4/trunk.jpg",
      "models/id4/rear-seat.jpg",
      "models/id4/sunroof.jpg",
      "models/id4/motor-compartment.jpg",
      "models/id4/key.jpg",
      "models/id4/charging-port.jpg",
      "models/id4/charging-port-2.jpg",
      "models/id4/driving-cabin.jpg",
    ],
  },

  {
    id: "corolla-hybrid",
    slug: "corolla",
    brand: "Toyota",
    model: "Corolla 1.8 Hybrid",
    year: 2025,
    stock: 15,
    heroImage: "models/corolla/front-view.jpg",
    descriptionShort: "Надійна гібридна Corolla",
    trims: [
      { id: "base", name: "Corolla 1.8 Hybrid", price: 30900, colors: ["Білий"], rangeKm: 1000, batteryKwh: 0, powerHp: 122, drive: "Передній" },
    ],
    gallery: [
      "models/corolla/front-view.jpg",
      "models/corolla/side-view.jpg",
      "models/corolla/front-left.jpg",
      "models/corolla/front-right.jpg",
      "models/corolla/trunk.jpg",
      "models/corolla/rear-view.jpg",
      "models/corolla/rear-seat.jpg",
      "models/corolla/detail.jpg",
      "models/corolla/engine.jpg",
      "models/corolla/key.jpg",
      "models/corolla/driving.jpg",
    ],
  },

  {
    id: "camry",
    slug: "camry",
    brand: "Toyota",
    model: "Camry 2.0HG",
    year: 2025,
    heroImage: "models/camry/front-view.jpg",
    descriptionShort: "Преміальний гібридний седан",
    trims: [
      { id: "elite", name: "Camry 2.0HG Еліт", price: 43500, stock: 11, colors: ["Білий"], rangeKm: 1200, batteryKwh: 0, powerHp: 160, drive: "Передній" },
      { id: "lux", name: "Camry 2.0HG Люкс", price: 46000, stock: 4, colors: ["Чорний"], rangeKm: 1200, batteryKwh: 0, powerHp: 160, drive: "Передній" },
    ],
    gallery: [
      "models/camry/front-view.jpg",
      "models/camry/side-view.jpg",
      "models/camry/front-left.jpg",
      "models/camry/rear-right.jpg",
      "models/camry/trunk.jpg",
      "models/camry/rear-seat.jpg",
      "models/camry/detail.jpg",
      "models/camry/steering-wheel.jpg",
      "models/camry/key.jpg",
      "models/camry/camry-badge.jpg",
      "models/camry/driver-seat.jpg",
      "models/camry/dashboard.jpg",
      "models/camry/passenger-seat.jpg",
    ],
  },

  {
    id: "corolla-cross",
    slug: "corolla-cross",
    brand: "Toyota",
    model: "Corolla Cross 2.0 Hybrid",
    year: 2024,
    heroImage: "models/corolla-cross/front-view.jpg",
    descriptionShort: "Компактний гібридний кросовер",
    trims: [
      { id: "sunroof", name: "Corolla Cross 2.0 (з люком)", price: 37200, stock: 2, colors: ["Білий"], rangeKm: 1100, batteryKwh: 0, powerHp: 131, drive: "Передній" },
      { id: "no-sunroof", name: "Corolla Cross 2.0 (без люка)", price: 35500, stock: 3, colors: ["Сірий"], rangeKm: 1100, batteryKwh: 0, powerHp: 131, drive: "Передній" },
    ],
    gallery: [
      "models/corolla-cross/front-view.jpg",
      "models/corolla-cross/side-view.jpg",
      "models/corolla-cross/front-left.jpg",
      "models/corolla-cross/front-right.jpg",
      "models/corolla-cross/trunk.jpg",
      "models/corolla-cross/rear-seat.jpg",
      "models/corolla-cross/rear-view.jpg",
      "models/corolla-cross/key.jpg",
      "models/corolla-cross/driving-cabin.jpg",
      "models/corolla-cross/with-sunroof.jpg",
      "models/corolla-cross/without-sunroof.jpg",
      "models/corolla-cross/engine.jpg",
      "models/corolla-cross/engine-2.jpg",
      "models/corolla-cross/front-seat.jpg",
    ],
  },

  {
    id: "rav4",
    slug: "rav4",
    brand: "Toyota",
    model: "RAV4 2.5 Hybrid",
    year: 2024,
    stock: 6,
    heroImage: "models/rav4/front-view.jpg",
    descriptionShort: "Урфривна гібридна RAV4",
    trims: [
      { id: "base", name: "RAV4 2.5 Hybrid", price: 48000, colors: ["Білий"], rangeKm: 1350, batteryKwh: 0, powerHp: 203, drive: "Повний" },
    ],
    gallery: [
      "models/rav4/front-view.jpg",
      "models/rav4/side-view.jpg",
      "models/rav4/front-left.jpg",
      "models/rav4/front-right.jpg",
      "models/rav4/trunk.jpg",
      "models/rav4/rear-view.jpg",
      "models/rav4/rear-seat.jpg",
      "models/rav4/key.jpg",
      "models/rav4/driving.jpg",
      "models/rav4/driver-door.jpg",
      "models/rav4/engine.jpg",
    ],
  },

  {
    id: "seal06",
    slug: "seal-06",
    brand: "BYD",
    model: "Seal 06 EV",
    year: 2025,
    stock: 2,
    heroImage: "models/seal-06/front-view.jpg",
    descriptionShort: "Стильний електричний седан",
    trims: [
      { id: "545", name: "Seal 06 EV 545", price: 32100, colors: ["Білий"], rangeKm: 545, batteryKwh: 65, powerHp: 150, drive: "Передній" },
    ],
    gallery: [
      "models/seal-06/front-view.jpg",
      "models/seal-06/side-view.jpg",
      "models/seal-06/front-left.jpg",
      "models/seal-06/front-right.jpg",
      "models/seal-06/rear-left.jpg",
      "models/seal-06/rear-right.jpg",
      "models/seal-06/trunk.jpg",
      "models/seal-06/rear-seat.jpg",
      "models/seal-06/detail.jpg",
      "models/seal-06/sunroof.jpg",
      "models/seal-06/key.jpg",
      "models/seal-06/driving.jpg",
      "models/seal-06/motor-detail.jpg",
      "models/seal-06/startup.jpg",
    ],
  },

  {
    id: "audi-q4",
    slug: "audi-q4",
    brand: "Audi",
    model: "Q4 e-tron 40",
    year: 2024,
    stock: 4,
    heroImage: "models/audi-q4/front-view.jpg",
    descriptionShort: "Преміальний електричний кросовер",
    trims: [
      { id: "40", name: "Audi Q4 e-tron 40", price: 38400, colors: ["Білий"], rangeKm: 520, batteryKwh: 82, powerHp: 204, drive: "Повний" },
    ],
    gallery: [
      "models/audi-q4/front-view.jpg",
      "models/audi-q4/side-view.jpg",
      "models/audi-q4/front-left.jpg",
      "models/audi-q4/front-right.jpg",
      "models/audi-q4/rear-left.jpg",
      "models/audi-q4/rear-seat.jpg",
      "models/audi-q4/steering-wheel.jpg",
      "models/audi-q4/sunroof.jpg",
      "models/audi-q4/motor.jpg",
      "models/audi-q4/charging.jpg",
      "models/audi-q4/key.jpg",
      "models/audi-q4/driving.jpg",
      "models/audi-q4/side-view-2.jpg",
      "models/audi-q4/driver-door.jpg",
    ],
  },
];

// Mapping models to PDF specifications
const pdfLinks = {
  "bz3x": [
    "Instructions/BZ3X-610-Max.pdf",
    "Instructions/BZ3X-520-Pro.pdf",
    "Instructions/BZ3X-520-ProPlus.pdf"
  ],
  "song-plus": ["Instructions/Song-Plus-EV-520-Luxury.pdf"],
  "yuan-plus": [
    "Instructions/Yuan-Plus-510-Transcendent.pdf",
    "Instructions/Yuan-Plus-510-Leading.pdf"
  ],
  "qin-l": [
    "Instructions/Qin-L-EV-470-Leading.pdf",
    "Instructions/Qin-L-EV-545-Excellent.pdf",
    "Instructions/Qin-L-EV-545-Transcendent.pdf"
  ],
  "id4": ["Instructions/ID4-Pure-Edition.pdf"],
  "corolla": ["Instructions/Corolla-1.8L-Hybrid-Pioneer.pdf"],
  "camry": ["Instructions/Camry-2.0HG-Hybrid-Brilliant.pdf"],
  "corolla-cross": [
    "Instructions/Corolla-Cross-2.0L-Pioneer.pdf",
    "Instructions/Corolla-Cross-2.0L-Elite.pdf"
  ],
  "rav4": ["Instructions/RAV4-2.5L-Hybrid-Elite-Plus.pdf"],
  "seal-06": ["Instructions/Seal-06-EV-545-Flagship.pdf"],
  "audi-q4": ["Instructions/Audi-Q4-e-tron-40-Innovation.pdf"]
};

function getPdfLinks(carSlug) {
  return pdfLinks[carSlug] || [];
}
