backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "portfolio"
    label: "Портфоліо"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: "Category",
          name: "category",
          widget: "hidden",
          default: "layout",
        }
      - { label: "Обкладинка картки", name: "image", widget: "image" }
      - {
          label: "Description UA",
          name: "desc_ua",
          widget: "text",
          required: false,
        }
      - {
          label: "Description EN",
          name: "desc_en",
          widget: "text",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "games"
    label: "Ігри"
    folder: "content/games"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Category", name: "category", widget: "hidden", default: "js" }
      - { label: "Обкладинка картки", name: "image", widget: "image" }
      - {
          label: "Description UA",
          name: "desc_ua",
          widget: "text",
          required: false,
        }
      - {
          label: "Description EN",
          name: "desc_en",
          widget: "text",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Блог"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: "Category",
          name: "category",
          widget: "hidden",
          default: "blog",
        }
      - { label: "Обкладинка картки", name: "image", widget: "image" }
      - {
          label: "Description UA",
          name: "desc_ua",
          widget: "text",
          required: false,
        }
      - {
          label: "Description EN",
          name: "desc_en",
          widget: "text",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects_json"
    label: "Projects Index"
    files:
      - label: "Projects JSON"
        name: "projects"
        file: "data/projects.json"
        fields:
          - { label: "Raw JSON", name: "content", widget: "text" }
