backend:
  name: github
  repo: "Gopdon32/DenyTeam"
  branch: "main"
  auth_type: "implicit"
  local_backend: false
  app_id: "Ov23liCffDpzNbJ9SL19"
  base_url: "https://api.netlify.com"
  site_id: "denyteam"

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects_json"
    label: "Projects Index"
    files:
      - label: "Projects JSON"
        name: "projects"
        file: "data/projects.json"
        fields:
          - { label: "Raw JSON", name: "content", widget: "text" }
